name: PowerShell Script Analyzer
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master
jobs:
  lint:
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: lint
      uses: devblackops/github-action-psscriptanalyzer@master
      with:
        sendComment: true
        failOnErrors: true
        failOnWarnings: false
        failOnInfos: false
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        settingsPath: .github/workflows/PSScriptAnalyzerSettings.psd1